---
- name: Configure system-wide audit policies
  ansible.windows.win_audit_policy_system:
    audit_type: "{{ item.audit_type }}"
    category: "{{ item.category | default(omit) }}"
    subcategory: "{{ item.subcategory | default(omit) }}"
  loop: "{{ windows_manage_audit_system_policies }}"
  loop_control:
    label: "{{ item.category | default(item.subcategory) }}"

- name: Remove audit rules
  ansible.windows.win_audit_rule:
    path: "{{ item.path }}"
    user: "{{ item.user }}"
    state: absent
  register: windows_manage_audit__removed_rules
  failed_when: >-
    windows_manage_audit__removed_rules is failed and
    (not windows_manage_audit_ignore_missing | bool or
     (windows_manage_audit__removed_rules.msg is defined and
      'not found/invalid' not in windows_manage_audit__removed_rules.msg and
      'lookup the identity' not in windows_manage_audit__removed_rules.msg))
  loop: "{{ windows_manage_audit_rules_remove }}"
  loop_control:
    label: "{{ item.user + ' -> ' + item.path }}"
  when: >-
    windows_manage_audit_rules_create
    | selectattr('path', 'match', '(?i)' ~ (item.path | regex_escape) ~ '$')
    | selectattr('user', 'match', '(?i)' ~ (item.user | regex_escape) ~ '$')
    | length == 0

- name: Create audit rules
  ansible.windows.win_audit_rule:
    path: "{{ item.path }}"
    user: "{{ item.user }}"
    rights: "{{ item.rights | default(omit) }}"
    audit_flags: "{{ item.audit_flags | default(omit) }}"
    inheritance_flags: "{{ item.inheritance_flags | default(omit) }}"
    propagation_flags: "{{ item.propagation_flags | default(omit) }}"
    state: present
  loop: "{{ windows_manage_audit_rules_create }}"
  loop_control:
    label: "{{ item.user + ' -> ' + item.path }}"
