---
galaxy_info:
  author: Bill Peck
  description: Role to manage services on Windows.
  company: Red Hat

  license: GPL-3.0-or-later

  min_ansible_version: 2.15.0

  platforms:
    - name: EL
      versions:
        - "8"

  galaxy_tags:
    - linux
    - system
    - ansible

dependencies: []
collections:
  - ansible.windows
...
