---
galaxy_info:
  role_name: windows_manage_service
  author: Bill Peck, Hen Yaish
  company: Red Hat, Inc.
  description: Manage the lifecycle of Windows services, including creation and reconfiguration.
  license: GPL-3.0-or-later
  min_ansible_version: "2.18"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
        - "2025"
  galaxy_tags:
    - windows
    - service
    - system
    - configuration
dependencies: []
collections:
  - ansible.windows
...
