---
# =============================================================================
# Windows Server 2025 DISA STIG Complete Compliance Example
# =============================================================================
# This playbook demonstrates a complete STIG hardening workflow for Windows
# Server 2025 including all 2025-specific features (Hotpatching, Next-Gen
# Credential Guard, AD 32k pages) and 2022+ features (DNS-over-HTTPS, TLS 1.3).
#
# Prerequisites:
# - Windows Server 2025
# - Administrative access
# - Azure Arc agent (optional, for hotpatching)
# - TPM 2.0 + UEFI + Secure Boot (for Credential Guard)
# =============================================================================

- name: Apply DISA STIG V1R1 compliance to Windows Server 2025
  hosts: windows_2025_servers
  gather_facts: true

  vars:
    # Report configuration
    stig_report_path: C:\compliance\reports\stig_v1r1_report.json
    stig_organization: "My Organization"
    stig_classification: "UNCLASSIFIED"

    # Compliance enforcement
    stig_fail_on_non_compliance: false
    stig_compliance_threshold: 95

    # Windows Server 2025 features
    enable_hotpatching: true
    enable_credential_guard: true
    enable_dns_over_https: true

  tasks:
    - name: Ensure compliance report directory exists
      ansible.windows.win_file:
        path: C:\compliance\reports
        state: directory

    - name: Apply DISA STIG V1R1 hardening with 2025 features
      ansible.builtin.include_role:
        name: infra.windows_ops.windows_manage_stig
      vars:
        # Execution controls
        windows_manage_stig_generate_report: true
        windows_manage_stig_report_format: "json"
        windows_manage_stig_report_path: "{{ stig_report_path }}"
        windows_manage_stig_fail_on_non_compliance: "{{ stig_fail_on_non_compliance }}"
        windows_manage_stig_compliance_threshold: "{{ stig_compliance_threshold }}"

        # Metadata
        windows_manage_stig_classification: "{{ stig_classification }}"
        windows_manage_stig_organization: "{{ stig_organization }}"

        # Windows Server 2025 features
        windows_manage_stig_hotpatching_enabled: "{{ enable_hotpatching }}"
        windows_manage_stig_credential_guard_enabled: "{{ enable_credential_guard }}"
        windows_manage_stig_dns_over_https_enabled: "{{ enable_dns_over_https }}"
        windows_manage_stig_dns_over_https_mode: 2  # 2=automatic, 3=enforce only

        # All STIG categories
        windows_manage_stig_categories:
          - account_policies
          - audit_policies
          - user_rights
          - security_options
          - registry_settings
          - system_services

    - name: Retrieve compliance report
      ansible.builtin.slurp:
        src: "{{ stig_report_path }}"
      register: stig_report_raw

    - name: Parse compliance report
      ansible.builtin.set_fact:
        stig_report: "{{ stig_report_raw.content | b64decode | from_json }}"

    - name: Display compliance summary
      ansible.builtin.debug:
        msg:
          - "============================================"
          - "DISA STIG V1R1 Compliance Report"
          - "============================================"
          - "System: {{ inventory_hostname }}"
          - "OS Version: {{ stig_report.detected_version }}"
          - "Benchmark: {{ stig_report.version }}"
          - "Total Controls: {{ stig_report.total_controls }}"
          - "Passed: {{ stig_report.passed_controls }}"
          - "Failed: {{ stig_report.failed_controls }}"
          - "Compliance Score: {{ stig_report.compliance_score }}%"
          - ""
          - "2025 Features:"
          - "  Hotpatching: {{ stig_report.version_features.has_hotpatching }}"
          - "  Credential Guard: {{ stig_report.version_features.has_nextgen_credential_guard }}"
          - "  DNS-over-HTTPS: {{ stig_report.version_features.has_dns_over_https }}"
          - "  TLS 1.3: {{ stig_report.version_features.has_tls_13_default }}"
          - "============================================"

    - name: Validate compliance threshold
      ansible.builtin.assert:
        that:
          - stig_report.compliance_score | float >= stig_compliance_threshold | float
        fail_msg: "Compliance score {{ stig_report.compliance_score }}% below threshold {{ stig_compliance_threshold }}%"
        success_msg: "Compliance threshold met: {{ stig_report.compliance_score }}%"
      when: stig_fail_on_non_compliance | bool
