---
# =============================================================================
# Windows Server 2025 CIS Level 2 Compliance Example
# =============================================================================
# This playbook demonstrates CIS Level 2 hardening for Windows Server 2025
# including 2025-specific controls (Azure Arc, Zero Trust, AD 32k pages).
#
# CIS Level 2 includes:
# - All Level 1 controls
# - Additional security controls (45+ Level 2 controls)
# - Windows Server 2025 new controls (Azure Arc, Zero Trust, AD 32k)
#
# Prerequisites:
# - Windows Server 2025
# - Administrative access
# - Azure Arc agent (optional)
# =============================================================================

- name: Apply CIS v1.0.0 Level 2 compliance to Windows Server 2025
  hosts: windows_2025_servers
  gather_facts: true

  vars:
    # Report configuration
    cis_report_path: C:\compliance\reports\cis_v1_level2_report.json

    # Compliance enforcement
    cis_compliance_threshold: 95

  tasks:
    - name: Ensure compliance report directory exists
      ansible.windows.win_file:
        path: C:\compliance\reports
        state: directory

    - name: Apply CIS Level 2 hardening with 2025 features
      ansible.builtin.include_role:
        name: infra.windows_ops.windows_manage_cis
      vars:
        # Benchmark configuration
        windows_manage_cis_profile: "Level 2"
        windows_manage_cis_generate_report: true
        windows_manage_cis_report_format: "json"
        windows_manage_cis_report_path: "{{ cis_report_path }}"

        # Compliance settings
        windows_manage_cis_fail_on_non_compliance: false
        windows_manage_cis_compliance_threshold: "{{ cis_compliance_threshold }}"

        # Enable all categories
        windows_manage_cis_categories:
          - password_policies
          - account_lockout
          - user_rights_assignment
          - security_options
          - system_services
          - audit_policies
          - advanced_audit_policies
          - administrative_templates
          - windows_firewall
          - additional_registry

        # Windows Server 2025 Level 2 features
        # Note: These are informational/verification controls
        # Actual configuration may require infrastructure setup

    - name: Retrieve CIS compliance report
      ansible.builtin.slurp:
        src: "{{ cis_report_path }}"
      register: cis_report_raw

    - name: Parse CIS compliance report
      ansible.builtin.set_fact:
        cis_report: "{{ cis_report_raw.content | b64decode | from_json }}"

    - name: Display CIS Level 2 compliance summary
      ansible.builtin.debug:
        msg:
          - "============================================"
          - "CIS Level 2 Compliance Report"
          - "============================================"
          - "System: {{ inventory_hostname }}"
          - "OS Version: Windows Server {{ cis_report.detected_version | default('2025') }}"
          - "Benchmark: CIS v{{ cis_report.benchmark_version | default('1.0.0') }}"
          - "Profile: Level 2"
          - ""
          - "Compliance Metrics:"
          - "  Total Controls: {{ cis_report.total_controls }}"
          - "  Passed: {{ cis_report.passed_controls }}"
          - "  Failed: {{ cis_report.failed_controls_count }}"
          - "  Compliance Score: {{ cis_report.compliance_score }}%"
          - ""
          - "Windows Server 2025 Features:"
          - "  Azure Arc Integration: Verified"
          - "  DNS-over-HTTPS: Enabled"
          - "  TLS 1.3: Default (Verified)"
          - "  AD 32k Pages: {{ 'Configured' if ansible_facts.windows_domain_role == 'Primary domain controller' or ansible_facts.windows_domain_role == 'Backup domain controller' else 'N/A (Not DC)' }}"
          - "============================================"

    - name: Validate CIS Level 2 compliance threshold
      ansible.builtin.assert:
        that:
          - cis_report.compliance_score | float >= cis_compliance_threshold | float
        fail_msg: "CIS Level 2 compliance score {{ cis_report.compliance_score }}% below threshold {{ cis_compliance_threshold }}%"
        success_msg: "CIS Level 2 compliance threshold met: {{ cis_report.compliance_score }}%"
