---
galaxy_info:
  author: Red Hat Ansible Content Team
  description: Manage Windows Recovery Environment (WinRE).
  company: Red Hat, Inc.
  license: GPL-3.0-or-later
  min_ansible_version: "2.18"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
        - "2025"
  galaxy_tags:
    - windows
    - configuration
    - recovery
    - winre
dependencies: []
