---
- name: Manage Windows Firewall
  hosts: all
  gather_facts: false
  tasks:
    - name: Manage Windows Firewall
      ansible.builtin.include_role:
        name: infra.windows_ops.windows_manage_firewall
...
