---
galaxy_info:
  role_name: windows_manage_scheduled_tasks
  author: Hen Yaish
  company: Red Hat, Inc.
  description: Create, enable, disable, and remove Windows scheduled tasks.
  license: GPL-3.0-or-later
  min_ansible_version: "2.18"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
        - "2025"
  galaxy_tags:
    - windows
    - scheduling
    - configuration
dependencies: []
