---
# https://docs.microsoft.com/windows/win32/intl/table-of-geographical-locations
windows_manage_locale_location: 244

# System locale (affects non-Unicode programs)
windows_manage_locale_system: en-US

# UI display language
windows_manage_locale_ui: en-US

# User locale (date, time, number formats)
windows_manage_locale_user: en-US

# Input method profiles
# A list of locale names (en-US;fi-FI) or hex code pairs (0409:0000040B;en-US)
windows_manage_locale_input: en-US

# Force updating Welcome screen settings even if locale config was not changed
windows_manage_locale_welcome_screen_update_always: false

# Reboot after locale changes
windows_manage_locale_reboot: true
