---
galaxy_info:
  role_name: windows_manage_file_copy
  author: Ansible Ecosystem Engineering team (@eco-ansible-content)
  company: Red Hat, Inc.
  description: Copy files and render templates to Windows hosts, optionally setting the path owner.
  license: GPL-3.0-or-later
  min_ansible_version: "2.18"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
        - "2025"
  galaxy_tags:
    - windows
    - files
    - configuration
dependencies: []
